services:
  basicvids_auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: ${APP_PORT:-8000}

    container_name: basicvids_auth
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    extra_hosts:
      - "${CUSTOM_HOST:-host.docker.internal}:host-gateway"
    volumes:
      - ${DATA_PATH:-./data}:/basicvids_auth/data
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      APP_PORT: ${APP_PORT:-8000}
    entrypoint: ["/basicvids_auth/entrypoint.sh"]