services:
  basicvids_auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basicvids_auth
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/basicvids_auth/data
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    entrypoint: ["/basicvids_auth/entrypoint.sh"]